language: python
python: 3.9
env:
  - TOX_ENV=py39
  - MAIL_SERVER=localhost
  - MAIL_PORT=1025
install:
  - pip install tox
before_script:
    - sudo redis-server /etc/redis/redis.conf --port 6379
script:
  - tox -e $TOX_ENV