name: "Application tests (via Tox)"
on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tox-gh-actions
        uses: fedora-python/tox-github-action@v0.4
        with:
          dnf_install: redis
